"""Phase 7: approval-bound execution of a persisted remediation proposal.

The proposal generated by Phase 6.1 becomes executable only after an explicit
operator approval bound to the proposal's canonical hash.

Security invariants:
* execution never accepts repository, source SHA, target file, or patch data;
  those values come only from the persisted proposal + authoritative incident
  deployment evidence;
* the approval must match the exact persisted proposal hash;
* before execution the hash is recomputed from persisted RCA/proposal fields
  and the deployment target is re-authorized against the incident;
* an already-created PR is idempotently returned instead of creating a
  second remediation;
* the existing RemediationOrchestrationService remains the only execution
  boundary for workspace/git/GitHub operations.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Callable

from incident_service.application.services.hotfix_validation_service import (
    HotfixValidationService,
)
from incident_service.application.services.proposal_generation_service import (
    compute_proposal_hash,
)
from incident_service.application.services.remediation_orchestration_service import (
    RemediationOrchestrationResult,
)
from incident_service.application.services.remediation_target_binding import (
    resolve_authoritative_deployment_target,
)
from incident_service.domain.entities.hotfix_proposal import HotfixProposal
from incident_service.domain.entities.root_cause_analysis import (
    RCA_EVIDENCE_KIND,
    RootCauseAnalysis,
)
from incident_service.domain.repository_interface import IncidentRepositoryPort

_HASH_PATTERN = re.compile(r"^[0-9a-f]{64}$")


class ProposalApprovalError(ValueError):
    """Approval cannot be safely applied to the persisted proposal."""


class ProposalExecutionError(RuntimeError):
    """Proposal failed the execution preconditions or execution boundary."""


@dataclass(frozen=True)
class ProposalApprovalResult:
    incident_id: str
    proposal: HotfixProposal


@dataclass(frozen=True)
class ProposalExecutionResult:
    incident_id: str
    proposal: HotfixProposal
    orchestration: RemediationOrchestrationResult | None
    reused_existing_pr: bool = False


class ProposalExecutionService:
    """Approves and executes the single persisted proposal for an incident."""

    def __init__(
        self,
        repository: IncidentRepositoryPort,
        orchestrator_factory: Callable[[], Any],
        validation_service: HotfixValidationService | None = None,
    ):
        self.repository = repository
        self.orchestrator_factory = orchestrator_factory
        self.validation = validation_service or HotfixValidationService()

    def approve(
        self,
        *,
        incident_id: str,
        proposal_id: str,
        proposal_hash: str,
        approved_by: str,
    ) -> ProposalApprovalResult:
        incident = self._load_incident(incident_id)
        proposal = self._find_proposal(incident.patch_proposals, proposal_id)

        normalized_hash = self._validate_hash(proposal_hash)
        normalized_approver = approved_by.strip()
        if not normalized_approver:
            raise ProposalApprovalError("approved_by must not be empty")

        if proposal.proposal_hash != normalized_hash:
            raise ProposalApprovalError(
                "approval hash does not match the persisted remediation proposal"
            )
        if not proposal.is_verified:
            raise ProposalApprovalError(
                "only a deterministically verified proposal can be approved"
            )
        if proposal.status == "PR_CREATED":
            raise ProposalApprovalError(
                "proposal already produced a remediation pull request"
            )
        if proposal.status == "APPROVED":
            if (
                proposal.approved_by == normalized_approver
                and proposal.approved_at is not None
            ):
                return ProposalApprovalResult(incident.id, proposal)
            raise ProposalApprovalError(
                "proposal is already approved by a different operator"
            )
        if proposal.status != "PROPOSED":
            raise ProposalApprovalError(
                f"proposal state {proposal.status!r} cannot be approved"
            )

        # Domain owns the lifecycle transition and stores the approval
        # identity/timestamp on the aggregate.
        try:
            incident.approve_remediation_proposal(
                proposal_id=proposal.id,
                approved_by=normalized_approver,
                expected_hash=normalized_hash,
            )
            self.repository.save_incident(incident)
        except ValueError as exc:
            raise ProposalApprovalError(str(exc)) from exc
        except Exception as exc:
            raise ProposalExecutionError(
                "proposal approval could not be persisted"
            ) from exc

        persisted = self._find_proposal(incident.patch_proposals, proposal.id)
        return ProposalApprovalResult(incident.id, persisted)

    def execute(
        self,
        *,
        incident_id: str,
        proposal_id: str,
        proposal_hash: str,
    ) -> ProposalExecutionResult:
        incident = self._load_incident(incident_id)
        proposal = self._find_proposal(incident.patch_proposals, proposal_id)

        normalized_hash = self._validate_hash(proposal_hash)

        # Idempotent terminal read: retrying an already-published proposal
        # does not invoke Git/GitHub again.
        if (
            proposal.status == "PR_CREATED"
            and proposal.pull_request_url
            and proposal.proposal_hash == normalized_hash
        ):
            return ProposalExecutionResult(
                incident_id=incident.id,
                proposal=proposal,
                orchestration=None,
                reused_existing_pr=True,
            )

        if proposal.status != "APPROVED":
            raise ProposalExecutionError(
                f"proposal must be APPROVED before execution; current state is {proposal.status!r}"
            )
        if proposal.proposal_hash != normalized_hash:
            raise ProposalExecutionError(
                "execution hash does not match the persisted remediation proposal"
            )
        if not proposal.is_verified:
            raise ProposalExecutionError(
                "approved remediation proposal is no longer deterministically verified"
            )
        if proposal.incident_id and proposal.incident_id != incident.id:
            raise ProposalExecutionError(
                "proposal incident identity does not match the requested incident"
            )
        if not proposal.repository or not proposal.source_sha:
            raise ProposalExecutionError(
                "approved proposal is missing trusted repository/source identity"
            )

        # Reconstruct the original RCA inputs used for the Phase 6.1 hash.
        rca = self._latest_rca(incident)
        if rca is None or rca.incident_id != incident.id:
            raise ProposalExecutionError(
                "approved proposal has no valid persisted RCA evidence"
            )
        if any(ref not in {item.id for item in incident.evidence} for ref in proposal.evidence_refs):
            raise ProposalExecutionError(
                "approved proposal references evidence that no longer exists on the incident"
            )

        expected_hash = compute_proposal_hash(
            incident_id=incident.id,
            root_cause=rca.root_cause,
            evidence_refs=rca.evidence_refs,
            repository=proposal.repository,
            source_sha=proposal.source_sha,
            file_paths=[proposal.target_filepath] if proposal.target_filepath else [],
            patch=proposal.diff_patch_payload,
            validation_plan=proposal.validation_plan,
            risk_class=proposal.risk_class,
        )
        if expected_hash != proposal.proposal_hash:
            raise ProposalExecutionError(
                "persisted proposal integrity check failed; refusing execution"
            )

        # Re-run the exact target binding at execution time. A deployment
        # record can change between proposal generation and approval.
        target = resolve_authoritative_deployment_target(incident)
        if target is None:
            raise ProposalExecutionError(
                "no authoritative DEPLOYED target remains bound to this incident"
            )
        if (
            target["repository_name"] != proposal.repository
            or target["source_sha"] != proposal.source_sha.strip().lower()
        ):
            raise ProposalExecutionError(
                "authoritative deployment target no longer matches the approved proposal"
            )

        # Re-run deterministic patch policy immediately before constructing
        # the execution orchestrator. This protects the execution boundary if
        # repository state or validation policy has changed since proposal
        # generation.
        try:
            path_ok = proposal.apply_verification_pass()
            safe, violations = self.validation.validate_patch(
                proposal,
                rca.confidence,
            )
        except Exception as exc:
            raise ProposalExecutionError(
                "proposal safety validation failed during execution preflight"
            ) from exc
        if not path_ok or not safe:
            detail = ", ".join(violations) if violations else "patch structure verification failed"
            raise ProposalExecutionError(
                f"approved proposal no longer satisfies deterministic safety rules: {detail}"
            )

        # Only now may the existing workspace/Git/GitHub execution boundary be
        # constructed. No caller-supplied target data crosses into it.
        orchestrator = self.orchestrator_factory()
        try:
            result = orchestrator.execute(
                incident_id=incident.id,
                proposal=proposal,
                repository_slug=proposal.repository,
                base_branch="main",
                validation_profile="incident_service",
                pr_title=None,
                pr_body=None,
            )
        except Exception as exc:
            raise ProposalExecutionError(
                "approved remediation could not complete its guarded execution path"
            ) from exc

        pull_request_url = result.pull_request_url
        if not isinstance(pull_request_url, str) or not pull_request_url.startswith(
            "https://github.com/"
        ):
            raise ProposalExecutionError(
                "remediation execution did not return a valid GitHub pull request URL"
            )

        proposal.pull_request_url = pull_request_url
        proposal.status = "PR_CREATED"
        proposal.executed_at = datetime.now(timezone.utc)
        try:
            incident.mark_remediation_pr_created(
                proposal_id=proposal.id,
                pull_request_url=pull_request_url,
            )
            self.repository.save_incident(incident)
        except ValueError as exc:
            raise ProposalExecutionError(str(exc)) from exc
        except Exception as exc:
            raise ProposalExecutionError(
                "remediation result could not be persisted"
            ) from exc

        return ProposalExecutionResult(
            incident_id=incident.id,
            proposal=proposal,
            orchestration=result,
            reused_existing_pr=False,
        )

    def _load_incident(self, incident_id: str):
        normalized = incident_id.strip()
        incident = self.repository.get_incident_by_id(normalized)
        if incident is None:
            raise ProposalExecutionError(f"Incident '{normalized}' not found")
        return incident

    @staticmethod
    def _find_proposal(proposals: list[HotfixProposal], proposal_id: str) -> HotfixProposal:
        normalized = proposal_id.strip()
        for proposal in proposals:
            if proposal.id == normalized:
                return proposal
        raise ProposalExecutionError(f"remediation proposal '{normalized}' not found")

    @staticmethod
    def _validate_hash(value: str) -> str:
        normalized = value.strip().lower()
        if not _HASH_PATTERN.fullmatch(normalized):
            raise ProposalExecutionError("proposal_hash must be a 64-character SHA-256 digest")
        return normalized

    @staticmethod
    def _latest_rca(incident) -> RootCauseAnalysis | None:
        candidates = [
            item
            for item in incident.evidence
            if item.kind == RCA_EVIDENCE_KIND
        ]
        if not candidates:
            return None
        candidates.sort(
            key=lambda item: (
                item.observed_at.timestamp()
                if item.observed_at.tzinfo
                else item.observed_at.replace(tzinfo=timezone.utc).timestamp(),
                item.id,
            ),
            reverse=True,
        )
        try:
            return RootCauseAnalysis.from_payload(dict(candidates[0].payload))
        except (TypeError, ValueError):
            return None
